### ISSUE TITLE
Mirakle is broken in Gradle 6.0

### ISSUE THREAD

**Issue by eugene-krivobokov** [skrugly/mirakle#24]
Mirakle fails in Gradle 6.0:

```
Caused by: java.lang.NoSuchMethodError: org.gradle.StartParameter.isRecompileScripts()Z
        at MirakleKt$booleanParamsToOption$6.invoke(Mirakle.kt:261)
        at MirakleKt$booleanParamsToOption$6.invoke(Mirakle.kt)
        at MirakleKt.startParamsToArgs(Mirakle.kt:245)
```

This parameters was deprecated in Gradle 5.6:
https://docs.gradle.org/5.6.4/javadoc/org/gradle/StartParameter.html#isRecompileScripts--

In Gradle 6.0 it is unavailable:
https://docs.gradle.org/6.0/javadoc/org/gradle/StartParameter.html

**Comment by skrugly** [comment]
Thanks for reporting. 
Fixed in `com.instamotor:mirakle:1.3.1`
